// Generated by gencpp from file kennedy/cputemp.msg
// DO NOT EDIT!


#ifndef KENNEDY_MESSAGE_CPUTEMP_H
#define KENNEDY_MESSAGE_CPUTEMP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kennedy
{
template <class ContainerAllocator>
struct cputemp_
{
  typedef cputemp_<ContainerAllocator> Type;

  cputemp_()
    : cputemp(0.0)  {
    }
  cputemp_(const ContainerAllocator& _alloc)
    : cputemp(0.0)  {
  (void)_alloc;
    }



   typedef float _cputemp_type;
  _cputemp_type cputemp;




  typedef boost::shared_ptr< ::kennedy::cputemp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kennedy::cputemp_<ContainerAllocator> const> ConstPtr;

}; // struct cputemp_

typedef ::kennedy::cputemp_<std::allocator<void> > cputemp;

typedef boost::shared_ptr< ::kennedy::cputemp > cputempPtr;
typedef boost::shared_ptr< ::kennedy::cputemp const> cputempConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kennedy::cputemp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kennedy::cputemp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kennedy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'kennedy': ['/home/faris/catkin_ws/src/kennedy/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kennedy::cputemp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kennedy::cputemp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kennedy::cputemp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kennedy::cputemp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kennedy::cputemp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kennedy::cputemp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kennedy::cputemp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f6d07e987c77d2cff438e6eabfa2bb2";
  }

  static const char* value(const ::kennedy::cputemp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f6d07e987c77d2cULL;
  static const uint64_t static_value2 = 0xff438e6eabfa2bb2ULL;
};

template<class ContainerAllocator>
struct DataType< ::kennedy::cputemp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kennedy/cputemp";
  }

  static const char* value(const ::kennedy::cputemp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kennedy::cputemp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 cputemp\n\
";
  }

  static const char* value(const ::kennedy::cputemp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kennedy::cputemp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cputemp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cputemp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kennedy::cputemp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kennedy::cputemp_<ContainerAllocator>& v)
  {
    s << indent << "cputemp: ";
    Printer<float>::stream(s, indent + "  ", v.cputemp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KENNEDY_MESSAGE_CPUTEMP_H
